---
- name: Configurar servidor web
  hosts: web
  become: true
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Asegurar que Nginx est치 en ejecuci칩n
      service:
        name: nginx
        state: started
        enabled: true

- name: Configurar base de datos
  hosts: db
  become: true
  tasks:
    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: true

    - name: Asegurar que MariaDB est치 en ejecuci칩n
      service:
        name: mariadb
        state: started
        enabled: true